name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.3"
    
    - name: Build Docker image
      run: |
        docker build -f docker/Dockerfile -t vit_floorplan:latest .
    
    - name: Deploy
      run: |
        echo "Add your deployment steps here"
